# Generated by Django 3.0.7 on 2020-07-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Food'), ('D', 'Drink'), ('S', 'Soup')], max_length=1),
        ),
    ]
