# Generated by Django 3.0.7 on 2020-07-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200709_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Food'), ('S', 'Soup'), ('D', 'Drink')], max_length=1),
        ),
    ]
