# Generated by Django 3.0.7 on 2020-07-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_orderitem_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Soup'), ('D', 'Drink'), ('F', 'Food')], max_length=1),
        ),
    ]
