# Generated by Django 3.0.7 on 2020-07-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200710_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('D', 'Drink'), ('S', 'Soup'), ('F', 'Food')], max_length=1),
        ),
    ]
